CREATE DATABASE IF NOT EXISTS `ha-db`;
USE `ha-db`;

CREATE TABLE IF NOT EXISTS access_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    server_name VARCHAR(50) NOT NULL,
    visit_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO access_log (server_name) VALUES ('DB_SYSTEM_READY');
